# Generated by Django 5.1.1 on 2025-04-29 08:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0006_loghistory_alter_otomatisasi_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loghistory',
            options={'ordering': ['-upload_date']},
        ),
        migrations.AddField(
            model_name='loghistory',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='otomatisasi',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='loghistory',
            name='status',
            field=models.CharField(default='Success', max_length=50),
        ),
        migrations.AlterField(
            model_name='loghistory',
            name='upload_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
