# Generated by Django 5.1.1 on 2025-05-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_alter_loghistory_options_loghistory_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='is_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='last_processed_row',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loghistory',
            name='status',
            field=models.CharField(default='Success', max_length=100),
        ),
    ]
