# Generated by Django 5.1.1 on 2025-05-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0008_uploadedfile_is_failed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loghistory',
            name='file_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
