# Generated by Django 5.1.1 on 2025-05-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0009_loghistory_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otomatisasi',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
