# Generated by Django 5.1.1 on 2025-05-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0010_alter_otomatisasi_file_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otomatisasi',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
