# Generated by Django 5.1.7 on 2025-05-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0011_alter_otomatisasi_file_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nikp', models.CharField(max_length=20, unique=True)),
                ('jenis_kelamin', models.CharField(max_length=10)),
                ('alamat', models.TextField()),
                ('nomor_hp', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
