# Generated by Django 5.1.7 on 2025-05-19 02:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0012_siswa'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogHistory2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('course_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('process_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('file_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
