# Generated by Django 5.1.7 on 2025-05-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0014_peserta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peserta',
            options={},
        ),
        migrations.AddField(
            model_name='peserta',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='alamat_kantor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='jabatan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='jenis_kelamin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='nama_lembaga',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='pendidikan_terakhir',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='telp_kantor',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='tempat_lahir',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
