# Generated by Django 5.1.7 on 2025-05-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0015_alter_peserta_options_peserta_alamat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loghistory2',
            name='asesor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loghistory2',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loghistory2',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loghistory2',
            name='handphone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='loghistory2',
            name='jadwal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loghistory2',
            name='lokasi_sertif',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loghistory2',
            name='skema',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loghistory2',
            name='tuk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
