# Generated by Django 5.1.7 on 2025-05-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0016_loghistory2_asesor_loghistory2_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loghistory2',
            name='asesor',
        ),
        migrations.RemoveField(
            model_name='loghistory2',
            name='city',
        ),
        migrations.RemoveField(
            model_name='loghistory2',
            name='email',
        ),
        migrations.RemoveField(
            model_name='loghistory2',
            name='handphone',
        ),
        migrations.RemoveField(
            model_name='loghistory2',
            name='jadwal',
        ),
        migrations.RemoveField(
            model_name='loghistory2',
            name='lokasi_sertif',
        ),
        migrations.RemoveField(
            model_name='loghistory2',
            name='skema',
        ),
        migrations.RemoveField(
            model_name='loghistory2',
            name='tuk',
        ),
    ]
