# Generated by Django 5.1.7 on 2025-05-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0017_remove_loghistory2_asesor_remove_loghistory2_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peserta',
            name='is_converted',
            field=models.BooleanField(default=False),
        ),
    ]
