# Generated by Django 5.1.7 on 2025-05-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0019_loghistory2_city_loghistory2_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loghistory2',
            name='asesor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loghistory2',
            name='jadwal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loghistory2',
            name='lokasi_sertif',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loghistory2',
            name='skema',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loghistory2',
            name='tuk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
