# Generated by Django 5.1.7 on 2025-05-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0020_loghistory2_asesor_loghistory2_jadwal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loghistory2',
            name='template',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
