# Generated by Django 5.1.7 on 2025-06-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0021_loghistory2_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loghistory2',
            name='template',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
