# Generated by Django 5.1.7 on 2025-06-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0022_alter_loghistory2_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='peserta',
            name='agama_kemdikbud',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='agama_lkp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='alat_transportasi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='asal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='handphone_ortu',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='jenis_tinggal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='kab_kota',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='kecamatan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='kelurahan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='kewarganegaraan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='kode_pos',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='layak_pip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='peserta',
            name='nama_ayah',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='nama_ibu_kandung',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='nama_ortu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='nik',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='nik_ortu',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='nisn',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='pekerjaan_ortu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='pendidikan_ortu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='penerima_kip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='peserta',
            name='penerima_kps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='peserta',
            name='penghasilan_ortu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='propinsi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='rt',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='rw',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='tanggal_lahir_ortu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='tanggal_masuk',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='tempat_lahir_ortu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='nomor_hp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
