# Generated by Django 5.1.7 on 2025-06-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0023_peserta_agama_kemdikbud_peserta_agama_lkp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peserta',
            old_name='nomor_hp',
            new_name='handphone',
        ),
        migrations.AlterField(
            model_name='peserta',
            name='kode_pos',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='layak_pip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='penerima_kip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='penerima_kps',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='rt',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='rw',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
