# Generated by Django 5.1.7 on 2025-06-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0024_rename_nomor_hp_peserta_handphone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPeserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(blank=True, max_length=10, null=True)),
                ('nik', models.CharField(blank=True, max_length=16, null=True)),
                ('tempat_lahir', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('nisn', models.CharField(blank=True, max_length=10, null=True)),
                ('agama_lkp', models.CharField(blank=True, max_length=50, null=True)),
                ('handphone', models.CharField(blank=True, max_length=15, null=True)),
                ('kewarganegaraan', models.CharField(blank=True, max_length=50, null=True)),
                ('jenis_tinggal', models.CharField(blank=True, max_length=50, null=True)),
                ('tanggal_masuk', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('nama_ortu', models.CharField(blank=True, max_length=100, null=True)),
                ('nik_ortu', models.CharField(blank=True, max_length=16, null=True)),
                ('pekerjaan_ortu', models.CharField(blank=True, max_length=100, null=True)),
                ('pendidikan_ortu', models.CharField(blank=True, max_length=100, null=True)),
                ('penghasilan_ortu', models.CharField(blank=True, max_length=100, null=True)),
                ('handphone_ortu', models.CharField(blank=True, max_length=15, null=True)),
                ('tempat_lahir_ortu', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_lahir_ortu', models.DateField(blank=True, null=True)),
                ('asal', models.CharField(blank=True, max_length=100, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('rt', models.CharField(blank=True, max_length=10, null=True)),
                ('rw', models.CharField(blank=True, max_length=10, null=True)),
                ('kecamatan', models.CharField(blank=True, max_length=100, null=True)),
                ('kelurahan', models.CharField(blank=True, max_length=100, null=True)),
                ('kab_kota', models.CharField(blank=True, max_length=100, null=True)),
                ('propinsi', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_ibu_kandung', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_ayah', models.CharField(blank=True, max_length=100, null=True)),
                ('agama_kemdikbud', models.CharField(blank=True, max_length=50, null=True)),
                ('penerima_kps', models.CharField(blank=True, max_length=10, null=True)),
                ('layak_pip', models.CharField(blank=True, max_length=10, null=True)),
                ('penerima_kip', models.CharField(blank=True, max_length=10, null=True)),
                ('kode_pos', models.CharField(blank=True, max_length=10, null=True)),
                ('alat_transportasi', models.CharField(blank=True, max_length=50, null=True)),
                ('pendidikan_terakhir', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_lembaga', models.CharField(blank=True, max_length=255, null=True)),
                ('jabatan', models.CharField(blank=True, max_length=100, null=True)),
                ('alamat_kantor', models.TextField(blank=True, null=True)),
                ('telp_kantor', models.CharField(blank=True, max_length=15, null=True)),
                ('kota', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_converted', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='loghistory2',
            old_name='jadwal',
            new_name='jadwal_cooperation',
        ),
    ]
