# Generated by Django 5.1.7 on 2025-06-03 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0025_manualpeserta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loghistory2',
            old_name='jadwal_cooperation',
            new_name='jadwal',
        ),
    ]
