# Generated by Django 5.1.7 on 2025-06-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0026_rename_jadwal_cooperation_loghistory2_jadwal'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=10),
        ),
    ]
